# Generated by Django 4.2.1 on 2023-05-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backdrop', models.CharField(max_length=255, null=True)),
                ('genres', models.JSONField(null=True)),
                ('imdb_id', models.CharField(max_length=255, null=True, unique=True)),
                ('original_language', models.CharField(max_length=255, null=True)),
                ('original_title', models.CharField(max_length=255, null=True)),
                ('overview', models.TextField(null=True)),
                ('poster', models.CharField(max_length=255, null=True)),
                ('release_date', models.CharField(max_length=255, null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('tagline', models.TextField(null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('vote_average', models.FloatField(null=True)),
                ('videos', models.JSONField(null=True)),
                ('br_certification', models.CharField(max_length=255, null=True)),
                ('us_certification', models.CharField(max_length=255, null=True)),
                ('catalogs', models.ManyToManyField(through='catalog.CatalogMovie', to='catalog.catalog')),
            ],
        ),
        migrations.AddField(
            model_name='catalogmovie',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.movie'),
        ),
    ]
