version: '3.8'

services:
  gateway:
    build: ../cloud/gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - auth
      - catalogs
    networks:
      - network
  auth:
    build: ../auth
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - network
  #payment:
    #build: ../payment
    #ports:
    #  - "8082:8082"
    #depends_on:
    #  - db
    #networks:
    #  - network 
  catalogs:
    build: ../catalogs
    ports:
      - "8083:8083"
    depends_on:
      - db
    networks:
      - network  
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  