version: '3.8'

services:
  gateway:
    build: ../cloud/gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - catalogs
    networks:
      - network

  auth:
    build: ../microservices/auth-service
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - network

  catalogs:
    build: ../microservices/catalog-service
    ports:
      - "8083:8083"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - TMDB_API_KEY=1dff2f0530f95ef25e34068a5c3bfea0
    depends_on:
      - db
    networks:
      - network

  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - network

volumes:
  pgdata:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
  