server:
  port: 8080

spring:
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      routes:
      - id: route1
        uri: http://auth:8081
        predicates:
        - Path=/auth/**
      - id: route2
        uri: http://catalogs:8083
        predicates:
        - Path=/catalog/**
      - id: route3
        uri: http://catalogs:8083
        predicates:
        - Path=/static/**,/media/**
      - id: route4
        uri: http://auth:8081
        predicates:
        - Path=/auth/**