server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: route1
        uri: http://auth:8081
        predicates:
        - Path=/auth/**
      - id: route2
        uri: http://catalogs:8083
        predicates:
        - Path=/catalog/**